### PR TITLE
use gulp-htmlmin instead of gulp-minify-html

### PR DESCRIPTION
**Pull request by nschloe**
[gulp-minify-html](https://www.npmjs.com/package/gulp-minify-html) uses [minimize](https://github.com/Moveo/minimize) to minimize HTML; [gulp-htmlmin](https://www.npmjs.com/package/gulp-htmlmin) uses the more advanced [html-minifier](https://github.com/kangax/html-minifier). The latter has numerous tweaks and options, all exposed in the gulp interface, including linting (not enabled for now).

### CODE REVIEW

**Comment by andrenarchy** [comment]
Looks good. However, the parameters should be tweaked:
```
-rw-rw-r-- 1 rollout_frontend rollout_frontend 64K Mär  2 00:51 branches/htmlmin/tmp/templates.js
-rw-rw-r-- 1 rollout_frontend rollout_frontend 46K Mär  2 01:11 branches/master/tmp/templates.js
```
htmlmin doesn't seem to remove whitespaces and newlines by default. Let's check this tomorrow.

**Comment by andrenarchy** [comment]
We should also enable HTML validation in this PR, see #50.

**Comment by nschloe** [comment]
```
-rw-rw-r-- 1 nschloe users 49K Mar  2 01:30 ./tmp/templates.js
```

**Comment by andrenarchy** [comment]
I peeked into the generated templates and tested the build: runs as expected.

**Pull request merged**
