### PR TITLE
[JS][HTML] Created team-page and added routes

### PR DESCRIPTION
**Pull request by pure180**

### CODE REVIEW

**Comment by andrenarchy** [comment]
Nice! I think we can keep small images like the user pics (all <=100kB) in the repo.

@nschloe: do you agree?

**Comment by nschloe** [comment]
Not keeping binary data in the repo has payed off in the past, and I think we shouldn't diverge from that. Can't we just take Gravatar? Otherwise I'd say we host them from somewhere.

**Comment by andrenarchy** [comment]
I can place the images here: https://paperhub.io/dev/static/

**Comment by nschloe** [comment]
> I can place the images here: https://paperhub.io/dev/static/

++

They should also be removed from the Git history in this PR.

**Pull request merged**
