### PR TITLE
Margin dropdown: editing+deleting of original comment+replies

### PR DESCRIPTION
**Pull request by andrenarchy**

### CODE REVIEW

**Comment by nschloe** [comment]
Deleting doesn't work as advertised right now.
Steps to reproduce:
Add article, add comment, dropdown delete, click "OK", receive the error
delete

**Comment by andrenarchy** [comment]
You need the discussion-delete branch of the backend (which can be merged btw). ;-)

**Comment by nschloe** [comment]
The edit field shows title and body unconditonally. It should probably adapt the same logic that the comment creation field has.

**Comment by andrenarchy** [comment]
Let's talk at c-base!

**Pull request merged**
